<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Arial', sans-serif;
            font-size: 11px;
            color: #1F2937;
            line-height: 1.4;
        }
        .header {
            border-bottom: 3px solid #D4AF37;
            padding: 15px 0;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            font-weight: bold;
            color: #1F2937;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 10px;
            color: #6B7280;
        }
        .meta-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
            padding: 10px;
            background-color: #F9FAFB;
            border: 1px solid #E5E7EB;
        }
        .meta-info div {
            font-size: 9px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }
        th {
            background-color: #374151;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 9px;
            font-weight: bold;
            border: 1px solid #1F2937;
        }
        td {
            padding: 6px 8px;
            border: 1px solid #E5E7EB;
            font-size: 9px;
        }
        tr:nth-child(even) {
            background-color: #F9FAFB;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 20px;
        }
        .stat-card {
            background-color: #F9FAFB;
            border: 1px solid #E5E7EB;
            padding: 10px;
            text-align: center;
        }
        .stat-card .label {
            font-size: 8px;
            color: #6B7280;
            margin-bottom: 5px;
        }
        .stat-card .value {
            font-size: 18px;
            font-weight: bold;
            color: #1F2937;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #E5E7EB;
            text-align: center;
            font-size: 8px;
            color: #6B7280;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }
        .badge-success {
            background-color: #D1FAE5;
            color: #065F46;
        }
        .badge-danger {
            background-color: #FEE2E2;
            color: #991B1B;
        }
        .badge-warning {
            background-color: #FEF3C7;
            color: #92400E;
        }
        .badge-info {
            background-color: #DBEAFE;
            color: #1E40AF;
        }
        @page {
            margin: 15mm;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title ?? 'Report' }}</h1>
        <p>{{ $subtitle ?? 'Ministry of Education - Organizational Chart Management System' }}</p>
    </div>

    <div class="meta-info">
        <div><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</div>
        <div><strong>Generated By:</strong> {{ auth()->user()->full_name ?? auth()->user()->name ?? 'System' }}</div>
    </div>

    @yield('content')

    <div class="footer">
        <p>This is an official document generated by the Ministry of Education Organizational Chart Management System</p>
        <p>Page generated on {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
